### ISSUE TITLE
Decripion in ansible galaxy wrong

### ISSUE THREAD

**Issue by 0xErnie** [jtyr/ansible-php_fpm#1]
from https://galaxy.ansible.com/jtyr/php_fpm/

> jtyr.php_fpm
> Role which installs the Bacula Director

**Comment by jtyr** [comment]
Thanks for reporting this. It has been [fixed](https://github.com/jtyr/ansible-php_fpm/commit/2c50bb3fc82581f2a4f2e1d98b8c4884a7d71104).
